### ISSUE TITLE
Out of memory  about train

### ISSUE THREAD

**Issue by Ruinmou** [erikalu/omnimatte#11]
my computer:  RTX 2080  11G   
RuntimeError: CUDA out of memory. Tried to allocate 118.00 MiB (GPU 0; 10.76 GiB total capacity; 8.79 GiB already allocated; 135.25 MiB free; 9.05 GiB reserved in total by PyTorch)

I should modify those parameters to reduce memory consumption

**Comment by Ruinmou** [comment]
python train.py --name tennis --dataroot ./datasets/tennis --gpu_ids 0

**Comment by SpeitzerPatrick** [comment]
i have the same issue, i dont know why

**Comment by erikalu** [comment]
Try a smaller batch size by passing in, e.g. ```--batch_size 8```

**Comment by SpeitzerPatrick** [comment]
> Try a smaller batch size by passing in, e.g. `--batch_size 8`

still the same problem, idk why 
### here is my "nvidia-smi",u can see there is no issues here
![2021-09-07_10-16](https://user-images.githubusercontent.com/20340182/132274055-ba61d029-7096-42bf-ae93-8042dd5d3437.png)
### This is the bugs here
Setting up a new session...
create web directory ./checkpoints/tennis/web...
/home/patrick/.local/lib/python3.8/site-packages/torch/nn/functional.py:3609: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
/home/patrick/.local/lib/python3.8/site-packages/torch/nn/functional.py:3981: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
/home/patrick/.local/lib/python3.8/site-packages/torch/nn/functional.py:3609: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
/home/patrick/.local/lib/python3.8/site-packages/torch/nn/functional.py:3981: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
/home/patrick/.local/lib/python3.8/site-packages/torch/nn/functional.py:3609: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
/home/patrick/.local/lib/python3.8/site-packages/torch/nn/functional.py:3981: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
/home/patrick/.local/lib/python3.8/site-packages/torch/nn/functional.py:3609: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
/home/patrick/.local/lib/python3.8/site-packages/torch/nn/functional.py:3981: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
Traceback (most recent call last):
  File "train.py", line 88, in <module>
    main()
  File "train.py", line 42, in main
    train(model, dataset, visualizer, opt)
  File "train.py", line 62, in train
    model.optimize_parameters()
  File "/home/patrick/projects/DL/omnimatte/models/omnimatte_model.py", line 170, in optimize_parameters
    self.forward()
  File "/home/patrick/projects/DL/omnimatte/models/omnimatte_model.py", line 116, in forward
    outputs = self.netOmnimatte(self.input, self.input_bg_flow, self.input_bg_warp, self.jitter_grid, self.index, self.do_cam_adj)
  File "/home/patrick/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/patrick/.local/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/patrick/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/patrick/projects/DL/omnimatte/models/networks.py", line 143, in forward
    rgba, flow, last_feat = self.render(input_i)
  File "/home/patrick/projects/DL/omnimatte/models/networks.py", line 97, in render
    rgba = self.final_rgba(x)
  File "/home/patrick/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/patrick/projects/DL/omnimatte/third_party/models/networks_lnr.py", line 155, in forward
    x = F.pad(x, [int(np.floor(padx)), int(np.ceil(padx)), int(np.floor(pady)), int(np.ceil(pady))])
  File "/home/patrick/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 4153, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 458.00 MiB (GPU 0; 5.79 GiB total capacity; 3.26 GiB already allocated; 301.62 MiB free; 3.85 GiB reserved in total by PyTorch)

**Comment by erikalu** [comment]
Try an even smaller batch size, like 1 or 2.

**Comment by SpeitzerPatrick** [comment]
> Try an even smaller batch size, like 1 or 2.

That worked for me ,thx.
